
server.port: 8101
spring:
  application.name: sms-config-server
  cloud.config:
    server.git:
      uri: https://github.com/seremwen/SMS-Config-Files.git
      default-label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1